using System;

namespace FuneralCallV2.Classes
{
	public class Search
	{
		public string[] columns            { get; set; }       // If searching, what columns ...
		public string[] search             { get; set; }       // If searching, what are we searching for ...
		public int      limit              { get; set; } = 15; // Number of results to return ...
		public int      page               { get; set; } = 1;  // Starting page ...
		public string[] order_by           { get; set; }       // One or more columns to order results by, should include order by direction as well ...
		public Boolean  exact_match_search { get; set; }       // Use = vs. LIKE
		public string   operand            { get; set; }       // Operator to use instead of = or LIKE, i.e. !=, <, >, etc ...
		public string   qualifier          { get; set; }       // OR / AND
	}
}